export const he = {
  "Fried hot pepper": "פלפל חריף מטוגן",
  Pkaila: "פקאילה",
  "Meat-Filled Pastry": "פסטלים",
  "Beet Kubbeh": "קובה סלק",
  "Meat-Filled Cigars": "סיגרים",
  Maklouba: "מקלובה",
  "Meatballs with Green Beans in Moroccan Red Sauce": "קציצות עם שעועית ירוקה",
  "Fried Eggplant": "חציל מטוגן",
  "Electric Hot Plate for Rent": "פלטה להשכרה",
  Water: "מים",
  Mirinda: "מירנדה",
  Sprite: "ספרייט",
  Soda: "סודה",
  "Coca-Cola Zero": "קולה זירו",
  "Coca-Cola": "קולה",
  "Couscous with Vegetables": "קוסקוס עם ירקות",
  "Pasta with tomato sauce": "פסטה ברוטב עגבניות",
  "Bottle of Grape Juice for Kiddush": "תירוש",
  "Omelette Challah with Toppings of Your Choice Combo": "קומבו חביתה",
  "Sabich Challah Combo": "קומבו סביח",
  "Vegetable Patties Challah Combo": "קומבו קציצות ירק",
  "Shakshuka Challah Combo": "קומבו שקשוקה",
  "Fish Patties Challah Combo": "קומבו קציצות דג",
  "Hamburger Combo": "קומבו המבורגר",
  "Meatballs Challah Combo": "קומבו קציצות בשר",
  "Asado Challah Combo": "קומבו אסאדו",
  "Shawarma Pita Combo": "קומבו שווארמה",
  "Schnitzel Challah Combo": "קומבו שניצל",
  "Traditional Hamin": "חמין",
  "Jachnun- ג׳חנון": "ג׳חנון",
  "Fresh Schnitzel Platter": "מגש שניצל",
  "Egg Salad": "סלט ביצים",
  "Couple's Packages Friday Dinner": "חבילת זוג לשישי",
  "Spicy Moroccan Sea Bream Fillet": "דניס מרוקאי",
  "Spicy Moroccan Amnon Fillet": "אמנון מרוקאי",
  "Premium Disposable Cutlery": "סכו״ם",
  "Fresh Shabbat Challahs": "חלות שבת",
  "Shabbat Candles": "נרות שבת",
  "Roasted Potato": "תפוחי אדמה צלויים",
  "White Rice": "אורז",
  "Grilled Chicken with Potatoes": "עוף עם תפוחי אדמה",
  "Meatballs in Moroccan Red Sauce": "קציצות ברוטב מרוקאי",
  "Family Packages Friday Dinner": "חבילת משפחה לשישי",
  "Omelette Challah with Toppings of Your Choice": "חביתה בחלת",
  "Sabich Challah": "סביח בחלת",
  "Vegetable Patties Challah": "קציצות ירק בחלת",
  "Shakshuka Challah": "שקשוקה בחלת",
  "Challah Bread - medium": "חלה בינונית",
  "Fish Patties Challah": "קציצות דג בחלת",
  "Meatballs Challah": "קציצות בשר בחלת",
  "Asado Challah": "אסאדו בחלת",
  "Pita Shawarma": "שווארמה בפיתה",
  "Schnitzel Challah": "שניצל בחלת",
  "Yeast Cake": "עוגת שמרים",
  "Fruit Salad": "סלט פירות",
  Shakshuka: "שקשוקה",
  "Roast Beef with Mushrooms": "אסאדו עם פטריות",
  Mafrum: "מפרום",
  "Homemade Schnitzel": "שניצל",
  "Head Stew with Chickpeas and Peppers": "מרק ראש",
  Hamburger: "המבורגר",
  "Chicken Thighs in Mushroom Sauce": "פרגית ברוטב פטריות",
  "Chicken Shawarma": "שווארמה עוף",
  Potatoes: "תפוחי אדמה",
  "Mujadara Rice": "מג׳דרה",
  "Green Beans": "שעועית ירוקה",
  "French Fries": "צ׳יפס",
  "Challah Bread - big": "חלה גדולה",
  "Traditional Salad": "סלט ירקות",
  Tahini: "טחינה",
  Carrot: "גזר מזרחי",
  Matbucha: "מטבוחה",
  "Homemade pickles": "חמוצי הבית",
  "Homemade Hummus": "חומוס",
  "Green Tahini": "טחינה ירוקה",
  "Green salad": "סלט ירוק",
  "Eggplant in Mayonnaise": "חציל במיונז",
  Cabbage: "כרוב לבן",
  "Beet Salad": "סלק",
};
